# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy .NET Core MVC to IIS

on:
  push:
    branches: [ "dev-release" ]
  pull_request:
    branches: [ "dev-release" ]

jobs:
  build:

    runs-on: self-hosted  # Dùng runner đã cài đặt trên máy chủ IIS
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add NuGet.org Packages Source If Not Exists
      shell: powershell
      run: |
        # Check if the source exists using its name
        $exists = dotnet nuget list source | Select-String -Pattern "nuget.org" -Quiet
    
        if (-not $exists) {
          dotnet nuget add source --name "nuget.org" "https://api.nuget.org/v3/index.json"
          Write-Host "NuGet.org source added successfully."
        } else {
          Write-Host "NuGet.org source already exists. Skipping."
        }
    - name: Add github Packages Source If Not Exists
      shell: powershell
      run: |
        # Check if the source exists using its name
        $exists = dotnet nuget list source | Select-String -Pattern "github" -Quiet
    
        if (-not $exists) {
          dotnet nuget add source --username ngm-cong --password ${{ secrets.GIT_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ngm-cong/index.json"
          Write-Host "NuGet.org source added successfully."
        } else {
          Write-Host "NuGet.org source already exists. Skipping."
        }
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    # Dừng Application Pool trước khi publish
    - name: Stop Application Pool
      run: C:\Windows\System32\inetsrv\appcmd.exe stop apppool /apppool.name:"HPDQ.WebSupport"
      shell: powershell

    - name: Publish API
      run: dotnet publish "HPDQ.WebSupport.csproj" --configuration Release --output 'C:\IIS\HPDQ.WebSupport'
        
    # Khởi động lại Application Pool sau khi publish
    - name: Start Application Pool
      run: C:\Windows\System32\inetsrv\appcmd.exe start apppool /apppool.name:"HPDQ.WebSupport"
      shell: powershell
